import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import type { Course } from "@codewit/interfaces";

// the query key to use when searching for all courses
export function courses_query_key(): ["courses"] {
  return ["courses"];
}

// a wrapper function around useQuery for requesting all courses from the server
export function use_courses_query() {
  return useQuery({
    queryKey: courses_query_key(),
    queryFn: () => axios.get<Course[]>("/api/courses").then(r => r.data),
  });
}

// the query key to use when selecting a single course
//
// the `course_id` param should be the value generated by the server
//
// the `admin` param indicates if you are attempting to request admin
// level information
export function single_course_query_key(course_id: string, admin: boolean): ["course_id", string, boolean] {
  return ["course_id", course_id, admin];
}

// a wrapper function around useQuery for requesting a single course from the
// server
export function use_single_course_query(course_id: string, admin: boolean = false) {
  return useQuery({
    queryKey: single_course_query_key(course_id, admin),
    queryFn: async () => {
      try {
        let url = `/api/courses/${course_id}`;

        if (admin) {
          url += "?admin=1";
        }

        let result = await axios.get(url);

        return result.data;
      } catch(err) {
        if (axios.isAxiosError(err)) {
          if (err?.response?.status === 404) {
            return null;
          }
        }

        throw err;
      }
    }
  });
}
