FROM node:20-alpine

ARG MODE=dev
ENV MODE=$MODE
ENV NODE_ENV=$MODE

WORKDIR /codewit

COPY package.json ./
RUN npm install

COPY . .

EXPOSE $PORT

CMD [ "sh", "-c", "if [ \"$MODE\" = 'dev' ]; then npm run frontend-dev; else npm run build:client && npm run start:client; fi" ]