version: "3.8"

services:
  app:
    image: registry.digitalocean.com/codewitus/app:latest
    environment:
      - DB_HOST=DB_HOST
      - DB_USER=DB_USER
      - DB_PASSWORD=DB_PASSWORD
      - DB_NAME=DB_NAME
      - DB_PORT=DB_PORT
      - API_PORT=3000
      - API_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FRONTEND_URL=http://localhost:80
    ports:
      - "3000:3000"
    networks:
      - codewitus
    labels:
      - "kompose.service.type=ClusterIP"

  frontend:
    image: registry.digitalocean.com/codewitus/frontend:latest
    ports:
      - "3001:3001"
    networks:
      - codewitus
    environment:
      - API_PORT=80
      - API_HOST=nginx
    labels:
      - "kompose.service.type=ClusterIP"
      - "kompose.service.expose=true"
      - "kompose.service.ingress=true"

  codeeval:
    image: registry.digitalocean.com/codewitus/codeeval:latest
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENABLE_CPP=false
    ports:
      - "3002:3002"
    networks:
      - codewitus
    labels:
      - "kompose.service.type=ClusterIP"

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    networks:
      - codewitus

networks:
  codewitus:
    driver: bridge