version: '3.9'

services:
  codewitus_db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=rohith
      - POSTGRES_DB=codewitus_db

  app:
    depends_on:
      - codewitus_db
    build:
      dockerfile: Dockerfile.backend
    environment:
      - DB_HOST=codewitus_db
      - PORT=3000
    restart: unless-stopped
    ports:
      - 3000:3000
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        - path: api/
          target: /codewit/api/
          action: sync
    stdin_open: true
    tty: true
    

  frontend:
    depends_on: 
      - app
      - codewitus_db
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - 3001:3001
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        - path: client/
          target: /codewit/client/
          action: sync
    stdin_open: true
    tty: true
    