version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=rohith
      - POSTGRES_DB=codewitus_db

  # app:
  #   depends_on:
  #     - postgres
  #   build: .
  #   environment:
  #     - DB_HOST=postgres
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   stdin_open: true
  #   tty: true