name: Sync api-deploy (apply API heroku.yml)

on:
  push:
    branches: [ feature/production-build-deployment ]

permissions:
  contents: write

jobs:
  sync-api-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or update api-deploy from main
        run: |
          # Fetch remote branches
          git fetch origin

          # If api-deploy exists, update it; else create it from feature/production-build-deployment
          if git ls-remote --exit-code --heads origin api-deploy; then
            git checkout api-deploy
            # Merge feature/production-build-deployment (fast-forward when possible)
            git merge --no-edit origin/feature/production-build-deployment || true
          else
            git checkout -b api-deploy origin/feature/production-build-deployment
          fi

          # Always apply the API manifest
          cp heroku-api.yml heroku.yml
          git add heroku.yml

          # Commit only if there are changes
          git commit -m "chore: sync from feature/production-build-deployment and apply API heroku.yml" || echo "No changes to commit"

          # Push back to api-deploy
          git push origin HEAD:api-deploy